### ISSUE TITLE
navigator.plugins.length throws error when executing in jsdom

### ISSUE THREAD

**Issue by johnou** [Valve/fingerprintjs2#316]
Seems the `if (navigator.plugins) {` is not enough when running fingerprintjs2 in jsdom, when executing the js it throws the following exception..

```
Error: Uncaught [TypeError: Cannot read property 'length' of undefined]
    at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
    at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:235:9)
    at DocumentImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
    at DocumentImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
    at DocumentImpl.<anonymous> (node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:530:12)
    at node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
    at Object.check (node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:89:11)
    at Object.check (node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:92:23)
    at Object.check (node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:92:23)
    at Object.check (node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:92:23) TypeError: Cannot read property 'length' of undefined
    at e.getRegularPlugins (https://abc/vendor.30cd4fbe.js:18:1430)
    at e.pluginsKey (https://abc/vendor.30cd4fbe.js:18:1338)
```

I was able to work around this by creating a shim but extra armor in the fingerprintjs2 library wouldn't hurt either.

**Comment by GrosSacASac** [comment]
can be closed
